### ISSUE TITLE
Design Initial Schema

### ISSUE THREAD

**Issue by danielbh** [merlin-mart/merlin-mart#11]

**Comment by Leighembee** [comment]
MODELS

USERS
-   First Name
-   Last Name
-   Email
-   Street
-   Apt
-   City
-   State
-   Country
-   Zip Code
-   isAdmin
-   Payment (?)
-   UserName(?)


PRODUCTS
 - Category
- Name
- Description
- Price
- Image


REVIEWS
- UserName
- Rating
- Title
- Description


ORDERS
- ProductId 
- Date
- Total Price (maybe hook?)


RELATIONSHIPS

User   
         => many products
         => many reviews
         => many orders

Products 
          => many reviews
          => many users

Reviews  
            => one product
             => one user

Orders  
            => many products
             => one user
